react/package-lock.json
react/package.json
react/src/api/canvas.ts
react/src/components/chat/Chat.tsx
react/src/components/chat/Markdown.tsx
react/src/components/chat/Message/Regular.tsx
react/src/components/chat/Message/ToolCallContent.tsx
react/src/components/chat/Message/ToolCallTag.tsx
react/src/components/home/CanvasCard.tsx
react/src/components/home/CanvasDeleteDialog.tsx
react/src/components/home/CanvasList.tsx
react/src/constants.ts
react/src/types/types.ts
server/routers/canvas.py

Add 「delete canvas」
Refactor Message Components

feat: Delete Canvas & refactor: Messages

---

react/src/App.tsx
react/src/api/chat.ts
react/src/assets/style/animations.css
react/src/assets/style/index.css
react/src/assets/style/shiny-text.css
react/src/components/chat/Chat.tsx
react/src/components/chat/IconCarousel.tsx
react/src/components/chat/Markdown.tsx
react/src/components/chat/Spinner.tsx
react/src/components/ui/scroll-area.tsx
react/src/components/ui/shiny-text.tsx
react/src/routes/canvas.$id.tsx
react/src/types/types.ts

add: loading icons
fix: chat api
feat: scroll bottom

refactor: loading & scroll

---

react/src/components/chat/IconCarousel.tsx
react/src/components/comfyui/InstallComfyUIDialog.tsx
react/src/components/common/DialogContent.tsx
react/src/components/home/CanvasDeleteDialog.tsx
react/src/components/settings/AddProviderDialog.tsx
react/src/components/ui/button.tsx
react/src/components/ui/dialog.tsx

refactor: Dialogs

---

react/src/components/settings/ComfyuiSetting.tsx
react/src/i18n/locales/en/settings.json
react/src/i18n/locales/zh-CN/settings.json
server/asset/default_comfy_t2i_workflow.json
server/routers/image_tools.py

Comfy image2

---

react/src/api/upload.ts
react/src/components/chat/ChatTextarea.tsx
server/routers/image_tools.py

I found that flux kontext to edit image, sometimes it didn't keep the original ratio, it's because the model doesn't know the original image ratio information. so i added the w h info into the attached image

Keep ratio

---

react/src/components/settings/ComfyuiSetting.tsx
react/src/components/settings/dialog/index.tsx
react/src/components/settings/dialog/providers.tsx
react/src/components/settings/dialog/sidebar.tsx
react/src/components/ui/sidebar.tsx

Ajust sidebar style
Fix "Add Providers" Button

fix: SettingsDialog

---

server/main.py
server/routers/agent.py
server/routers/image_generators.py
server/routers/image_tools.py
server/routers/ssl_test.py
server/utils/ssl_config.py

官方文档建议： https://docs.aiohttp.org/en/stable/client_advanced.html#example-use-certifi
1. 这个 PR 将 所有使用到 aiohttp.ClientSession 的地方都附上 CA 证书。
2. 添加了 ssl 的测试 api
打开应用后，可在浏览器通过以下地址测试：
- http://127.0.0.1:57988/api/test_ssl
- http://127.0.0.1:57988/api/test_ssl_full
- http://127.0.0.1:57988/api/ssl_status

feat: integrate aiohttp SSL handling & add SSL test api

---

react/package-lock.json
react/package.json
react/src/components/canvas/CanvasExcali.tsx
react/src/components/chat/Chat.tsx
react/src/hooks/use-websocket.ts
react/src/lib/event.ts
react/src/main.tsx
react/src/routes/canvas.$id.tsx
react/src/routes/index.tsx

feat: save image result on backend
refactor: websocket; replace CustomEvent with EventBus. Better types.

Save image & Refactor Websocket

---

react/src/components/chat/Chat.tsx
react/src/routes/canvas.$id.tsx

Fixed the issue where the canvas would change when the session changed

fix: session change

---

react/src/App.tsx
react/src/components/auth/LoginDialog.tsx
react/src/components/auth/UserMenu.tsx
react/src/components/settings/JaazSetting.tsx
react/src/stores/configs.ts

feat: global LoginDialog & JaazSetting add login button

---

react/src/api/auth.ts
react/src/api/config.ts
react/src/components/auth/LoginDialog.tsx
react/src/components/auth/UserMenu.tsx
react/src/components/chat/ModelSelector.tsx
react/src/components/settings/CommonSetting.tsx
react/src/components/settings/dialog/providers.tsx
react/src/constants.ts
react/src/contexts/configs.tsx
server/routers/config.py
server/routers/image_tools.py
server/routers/video_generators.py
server/services/chat_service.py
server/services/config_service.py
server/services/langgraph_service.py
server/tools/image_generators.py

1. provider config 更新后，不需要重启
2. model 下拉选框添加 provider 显示，更好识别

修复 config 热更新，不需要重启

---

react/src/components/settings/ComfyuiSetting.tsx
server/routers/settings.py

fix CORS issue when checking status of ComfyUI

---

react/src/components/chat/Markdown.tsx
react/src/components/chat/Message/TextFoldTag.tsx

fix some error about fold tag error and conceal <think> </think>

---

server/services/langgraph_service.py

replicate 生图报错：
```json
id: 'ry2jd8q75nrme0cqpw9vaambz4',
model: 'black-forest-labs/flux-kontext-max',
version: 'hidden',
input: {
aspect_ratio: '2:3',
prompt: "A charming illustration combining Hello Kitty with back-to-school elements. The design features Hello Kitty wearing a cute backpack, surrounded by school supplies like books, pencils, and an apple. The background is white to enhance the colors. The slogan 'Welcome Back to School' is elegantly designed in a flowing script, integrated with school-themed motifs like a pencil and ruler, creating a cohesive and visually appealing composition. The overall feel is cheerful and inviting, perfect for the back-to-school season."
},
logs: 'Using seed: 1760624081\n' +
'Generating...\n' +
'helpers.exceptions.prediction.ModelError: The input or …
```

fix: 为 agent system_prompt 添加错误处理

---

server/routers/image_tools.py
server/tools/image_generation_utils.py
server/tools/image_generators.py

refactor: 重构保存图像到画布的逻辑，添加画布锁管理以防止并发导致图片重叠

---

server/routers/image_router.py
server/tools/utils/image_canvas_utils.py
server/tools/video_generation/video_canvas_utils.py
server/utils/canvas.py

fix canvas position issue

---

react/src/components/canvas/pop-bar/index.tsx
react/src/components/settings/ComfyuiWorkflowSetting.tsx

Fix xy coordinate when image is below 0

---

server/routers/comfyui_execution.py
server/tools/utils/image_canvas_utils.py
server/utils/canvas.py

修复多张图生成的时候，检查状态异常的bug:
使用ComfyUI测试，10张生成成功
为了排查，使用火山豆包seedream3.0，10张也生成成功

fix issue about watching execution status in generating multi images

---

server/main.py
server/tools/comfy_dynamic.py
server/tools/utils/comfyui.py
server/tools/utils/image_canvas_utils.py
server/tools/video_generation/video_canvas_utils.py

支持ComfyUI多个组建的并行输出（包括静态图和视频，动图暂不支持）

feat: multi outputs on executinh on ComfyUI

---

react/src/components/chat/Markdown.tsx

fix <code> element runs out of the chat interface

---

server/services/tool_service.py
server/tools/generate_image_by_doubao_seededit_3_volces.py
server/tools/image_providers/volces_provider.py
server/tools/utils/image_generation_core.py

support seededit model
